stages:
  preprocess_data:
    cmd: make data_preprocessed
    deps:
    - src/f1_elo/data.py
    params:
    - data.results_csv
    - data.races_csv
    outs:
    - data/interim/preprocessed_data.csv
  clean_data:
    cmd: make data_features
    deps:
    - data/interim/preprocessed_data.csv
    - src/f1_elo/features.py
    params:
    - data.preprocessed_path
    - data.status_csv
    outs:
    - data/interim/features.csv
  create_model:
    cmd: make data_model
    deps:
    - data/interim/features.csv
    - src/f1_elo/model.py
    params:
    - data.features_path
    - data.metrics_path
    - data.params_path
    - model.start_score
    - model.opt_params
    outs:
    - data/interim/modelled_data.csv
    - models/params.yaml:
        cache: false
    metrics:
    - models/metrics.json:
        cache: false

