data:
  constructors_csv: 'data/raw/constructors.csv'
  drivers_csv: 'data/raw/drivers.csv'
  results_csv: 'data/raw/results.csv'
  status_csv: 'data/raw/status.csv'
  races_csv: 'data/raw/races.csv'
  preprocessed_path: 'data/interim/preprocessed_data.csv'
  features_path: 'data/interim/features.csv'
  modelled_path: 'data/interim/modelled_data.csv'
  gott_path: 'data/processed/gott.csv'
  rank_path: 'data/processed/rank.csv'
  metrics_path: 'models/metrics.json'
  params_path: 'models/params.yaml'
  
model:
  opt_params:
    pbounds:
      'c': [10, 1000]
      'k': [10, 1000]
      'w': [0, 2]
    'n_iter': 20
    'init_points': 20
    'random_state': 1
  start_score: 1500