[tool.poetry]
name = "f1-analysis"
version = "0.1.0"
description = ""
authors = ["mwtmurphy <mitchell@motorway.co.uk>"]
readme = "README.md"
packages = [{include = "f1_analysis"}]

[tool.poetry.dependencies]
python = "3.10.*"
fastf1 = "^3.1.4"
streamlit = "^1.28.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.26.0"
matplotlib = "^3.8.1"
seaborn = "^0.13.0"
plotly = "^5.18.0"
nbformat = "^5.9.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
